apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgCr3Ri9k8JkK0N4osKllI487yKB8G//rxvZDWPe4byzD/p2jvYV9E4Q5DmUs17IKdItkDF5EPzoA3xrmeHy9mgqZ7u1q17y+X7Cr+LycY6hE8eam7CYWuRJO2bzcNYVYgfztn6SurG6uHt3DOWaGlcI3igcsGlgUhrNASy8Bq3bKJFn4ptXm24b83i9Ba4lQxdf3NiLM4qnow0r166Wps7eOKs1YdhG/Y100Rombbyy+565MurlfTP+mlpraURxA6CgpqVdtq33kDlYLu4rvbHuLDa8BlbWIZ8OsvgOd9T287t5VAmUpoGsFZO2NjIAdGfWtIWL9MruJV48EOt6QyFBwFQuP5PV9ZOgzIuY8MoEu66NgJu9Nwqiy3cbt5UzChM3HADosYj8C50rkHO5SMJiyBJY+d/S9d2D5waylD7lOIgahO+jWs2nl7u4ktx9P135scZgr+JWEtS2/yz0JpMoz1YCGpF/rlOs8Ha204JR5JWvgtu81q6QwuFEcEuRcG57yfvKigABA/NPQiExSJ2iRc7vASPr7HM5XBxMdNNvpI1gsFqlGq2xQtn6xNPBjFK3/wPZWK/tIp2+eSQGukHOXgrN1R4M44+mNTj6iBFPV7uw+iGAqxP5nUnpeAtPd+mNVrLFzw/yTh+aI2bD/YJCsPTVT74PBuKK5rDoa3QdFUKk75qsQjXp0rw5KdEKyq4nIITEjMduaA==
    DB_USER: AgCUJSrBgGA9I1UY2SrElrvoa48fqomeggQeHZRXe4oZDeYgPv5eSSLS6QXlqEnm1NG0K5zFk798ndoqYMQI+fg/Vi6wpDyowaNFdpKtn56H+VrIjrbEqML5ZoqE2kWGGXU7TZjLfw9BMXG71zaPggrPih/+pYkJSNm61f9LQOuo4WvNQDoCR5ymLsbEmBLcoBlmgWOIwJBESCry9DeXyexwsmrOk/Iyxdn4hFPGyOvsj3kULPXDsDtcG9qm23aK8XJvS4uKkpw7MKrjpHCQ76vomNXGiNHA9j4Bhpf4aWgAn62BzRqVIpC82UzkkKyqp2e8tyESPz27H14AuptV4I1SdEHMkMapxf6uwOTZfqVF2tBh4nWxdx1e8aRA5tDgBgWWdSINnn570ObfUz2sKr8PMu1BsCuU0z71CUQl8CIjL5xrRw7rcL8uis0IDChvBaxZrnS6I5uIMhiiauJgBzOo10uRlDKxPg4Ld/i4SZn4tqL7ANsOwHd1oSqtxThmnbF3N+Tt9mwTGcpagbXndbwyozcbJFi8q2bb3kdgV3nk9ZRt6q01MKTsK7n3C2u0lh5FQBGxQIJWixtCoYeo8p1N1klX2QXvh3+BREydCkoXouHX33KPNZwMqBGnN5SA6O/JrlyhpfJ84DT+rGYIa1nZN6Zll5TO91/VFYfthlVI8iPHFszF+OX7q22rjAfgCSortm2Opl8hvw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

