# (C) Copyright 2021 Syncsort Incorporated. All rights reserved.

{{- include "sch.config.init" (list . "documentSvc.sch.chart.config.values") -}}
{{- $compName :=  .sch.chart.components.dashboard.name }}
{{- if and (.Capabilities.APIVersions.Has "monitoringcontroller.cloud.ibm.com/v1") .Values.dashboard.enabled }}
apiVersion: monitoringcontroller.cloud.ibm.com/v1
kind: MonitoringDashboard
metadata:
  name: {{ include "sch.names.fullCompName" (list . $compName) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . $compName) | indent 4 }}
spec:
  enabled: true
  data: |-
{{ .Files.Get "ibm_cloud_pak/pak_extensions/dashboards/grafanadashboard.json" | indent 4 }}
{{- end }}